services:
  - type: web
    name: maturitni-prace
    env: docker
    dockerfilePath: ./Dockerfile
    dockerCommand: php artisan serve --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_NAME
        value: "Maturitni Prace"
      - key: DB_CONNECTION
        value: sqlite
    buildCommand: |
      cp .env.example .env
      touch database/database.sqlite
    disk:
      name: sqlite-data
      mountPath: /var/www/html/database
      sizeGB: 1